### ISSUE TITLE
Rightscale oauth support

### ISSUE THREAD

**Issue by areznikov-kabam** [rightscale/right_chimp#84]
RightScale personal OAuth Token support is missing.

**Comment by areznikov-kabam** [comment]
Created pull request 
https://github.com/rightscale/right_chimp/pull/85

**Comment by markitoxs** [comment]
Hello!

First of all, let me apologize for completely missing this. I just happened to notice it today.

Instead of having you merge the latest and fix conflicts' ive just gone ahead and added the feature directly.

https://github.com/rightscale/right_chimp/commit/26a2341688a11d5498d5390ee2e6153d4365e981
